### Создание нового рецепта 1
POST http://localhost:8080/recipes
Content-Type: application/json

{
    "recipeName": "Яишница",
    "timeForPreparing": 10,
    "ingredients": [
      {
        "ingredientName": "Яйца",
        "quantityOfIngredients": 2,
        "unit": "шт"
      },
      {
      "ingredientName": "Соль",
      "quantityOfIngredients": 0,
      "unit": "по вкусу"
      }
    ],
    "cookingSteps": [
    "1 Разогреть",
    "2 Пожарить",
    "3 Съесть"
    ]
}


### Создание нового рецепта 2
POST http://localhost:8080/recipes
Content-Type: application/json

{
    "recipeName": "Омлет",
    "timeForPreparing": 15,
    "ingredients": [
{
    "ingredientName": "Яйца",
    "quantityOfIngredients": 5,
    "unit": "шт"
    },
{
    "ingredientName": "Молоко",
    "quantityOfIngredients": 1,
    "unit": "л"
    }
    ],
    "cookingSteps": [
    "1 Разогреть",
    "2 Пожарить",
    "3 Съесть"
    ]
}

### Получение всех рецептов
GET http://localhost:8080/recipes

### Получение рецепта по id
GET http://localhost:8080/recipes/1

### Изменение рецепта по id
PUT http://localhost:8080/recipes/1
Content-Type: application/json

{
    "recipeName": "Суп",
    "timeForPreparing": 50,
    "ingredients": [
{
    "ingredientName": "Картошка",
    "quantityOfIngredients": 500,
    "unit": "г"
    },
{
    "ingredientName": "Мясо",
    "quantityOfIngredients": 400,
    "unit": "г"
    }
    ],
    "cookingSteps": [
    "1 Разогреть",
    "2 Сварить",
    "3 Съесть"
    ]
}

### Удаление рецепта по id
DELETE http://localhost:8080/recipes/1
